### ISSUE TITLE
WCF Net Pipe

### ISSUE THREAD

**Issue by Dweston88** [Microsoft/wcf-docker#16]
I am trying to use net.pipe but have had no luck getting it to work. I believe it has to do with trying to reference localhost.

Server Information
OS: Windows Server 2016
DockerFile: FROM microsoft/windowsservercore
Docker for Windows
 
Internet -> Ports 80 and 443 -> ASP.NET MVC Front End -> net.pipe -> WCF Service
 
WCF End Point
<endpoint address="net.pipe://localhost/WCFService.svc" binding="netNamedPipeBinding" contract=”WCFService.Contract " bindingConfiguration="LargeMessagePipe" />

**Comment by zhenlan** [comment]
@Dweston88, do you have `NET-WCF-Pipe-Activation45` enabled in the container WCF service is running? Is the MVC app in the same container of the WCF service?

**Comment by Dweston88** [comment]
Yes and Yes. 

DockerFile
RUN Install-WindowsFeature -name NET-WCF-HTTP-Activation45

RUN Import-Module "WebAdministration"; \
    New-Item IIS:\AppPools\NewPool; \
	New-Item IIS:\Sites\NewSite -physicalPath 'C:\Service' -bindings @{protocol='https';bindingInformation='*:19001:'}; \
	New-ItemProperty 'IIS:\Sites\NewSite' -name bindings -Value @{protocol='net.pipe';bindingInformation='localhost/servicelocation'}; \
	Set-ItemProperty IIS:\Sites\NewSite -name applicationPool -value NewPool; \
	Set-ItemProperty IIS:\Sites\NewSite -name EnabledProtocols -Value 'http,net.pipe'

**Comment by zhenlan** [comment]
I don't see you have NET-WCF-**Pipe**-Activation45...

**Comment by Dweston88** [comment]
I adjusted the comment. I have all of them installed.

**Comment by Dweston88** [comment]
@zhenlan Do you have any samples for how this would work? I can get this same exact setup working on a Win Server 2016 IIS but when I try it with containers I have no luck.

**Comment by zhenlan** [comment]
@Dweston88 do you mind to share your sample? We may need to take a further look.

@KKhurin, @mconnew any ideas why this might not work?

**Comment by Dweston88** [comment]
@zhenlan @KKhurin @mconnew 

Listed below is the full docker file.

Steps to Run DockerFile
1. docker build -t my_image .
2. docker run -it -d -p 80:80 -p 443:443 --name testdocker my_image
3. navigate to mysite.domain.com - MVC web loads, WCF does not

FROM microsoft/windowsservercore

SHELL ["powershell"]
RUN Install-WindowsFeature -name NET-Framework-45-ASPNET -IncludeAllSubfeature
RUN Install-WindowsFeature -name Web-Asp-Net45 -IncludeAllSubfeature
RUN Install-WindowsFeature -name Web-Server -IncludeManagementTools
RUN Install-WindowsFeature -name Web-Common-Http -IncludeAllSubfeature
RUN Install-WindowsFeature -name Web-Health -IncludeAllSubFeature
RUN Install-WindowsFeature -name Web-Performance -IncludeAllSubFeature
RUN Install-WindowsFeature -name Web-Security -IncludeAllSubFeature
RUN Install-WindowsFeature -name Web-Mgmt-Tools -IncludeAllSubFeature
RUN Install-WindowsFeature -name Web-Scripting-Tools -IncludeAllSubFeature
RUN Install-WindowsFeature -name NET-WCF-Pipe-Activation45
RUN Install-WindowsFeature -name NET-WCF-TCP-Activation45
RUN Install-WindowsFeature -name NET-WCF-HTTP-Activation45
RUN Install-WindowsFeature -name FS-FileServer
RUN Install-WindowsFeature -name Web-WebSockets
RUN Install-WindowsFeature -name BitLocker

#RUN get-windowsfeature

RUN Remove-Website 'Default Web Site';

COPY ["SSLCert.pfx", "/Certs/SSLCert.pfx"]

RUN certutil -importpfx -p "Password" "C:\Certs\SSLCert.pfx";

COPY ["AzureEnc.pfx", "/Certs/AzureEnc.pfx"]

RUN certutil -importpfx -p "Password" "C:\Certs\AzureEnc.pfx";

# Set up website: mvcweb
RUN New-Item -Path 'C:\Services\mvcweb' -Type Directory -Force;

RUN Import-Module "WebAdministration"; \
    New-Item IIS:\AppPools\mvcwebpool; \
	New-Item IIS:\Sites\mvcweb -physicalPath 'C:\Services\mvcweb' -bindings @{protocol='http';bindingInformation='*:80:mysite.domain.com'}; \
	Set-ItemProperty IIS:\Sites\mvcweb -name applicationPool -value mvcwebpool
	
RUN New-WebBinding -name "mvcweb" -Protocol https -HostHeader "mysite.domain.com" -Port 443 -SslFlags 1; \
$certificate = Get-ChildItem Cert:\LocalMachine\My | ? { $_.FriendlyName -like '*.domain.com' }; \
New-Item -Path 'IIS:\SslBindings\!443!mvcweb' -Value $certificate -SSLFlags 1

COPY ["mvcweb", "/Services/mvcweb"]

RUN $path='C:\Services\mysite.domain.com'; \
    $acl = Get-Acl $path; \
    $newOwner = [System.Security.Principal.NTAccount]('BUILTIN\IIS_IUSRS'); \
    $acl.SetOwner($newOwner); \
    dir -r $path | Set-Acl -aclobject  $acl
	
# Set up website: wcf
RUN New-Item -Path 'C:\Services\wcf' -Type Directory -Force; 

RUN Import-Module "WebAdministration"; \
    New-Item IIS:\AppPools\wcfpool; \
	New-Item IIS:\Sites\wcf-physicalPath 'C:\Services\wcf' -bindings @{protocol='https';bindingInformation='*:19001:'}; \
	New-ItemProperty 'IIS:\Sites\wcf' -name bindings -Value @{protocol='net.pipe';bindingInformation='localhost/folder1/folder2'}; \
	Set-ItemProperty IIS:\Sites\wcf -name applicationPool -value wcfpool; \
	Set-ItemProperty IIS:\Sites\wcf -name EnabledProtocols -Value 'http,net.pipe'
	
RUN New-WebBinding -Name 'wcf' -Protocol 'https' -Port 19001 -HostHeader 'mysite.domain.com' -SslFlags 0; \
$certificate = Get-ChildItem Cert:\LocalMachine\My | ? { $_.FriendlyName -like '*.domain.com' }; \
New-Item -Path 'IIS:\SslBindings\!19001!mysite.domain.com' -Value $certificate -SSLFlags 0
	
COPY ["wcf", "/Services/wcf"]

RUN $path='C:\Services\wcf'; \
    $acl = Get-Acl $path; \
    $newOwner = [System.Security.Principal.NTAccount]('BUILTIN\IIS_IUSRS'); \
    $acl.SetOwner($newOwner); \
    dir -r $path | Set-Acl -aclobject  $acl
	
EXPOSE 80

EXPOSE 443

**Comment by zhenlan** [comment]
@Dweston88, sorry, I did not get a chance to look into this yet. Did you figure it out? It will be valuable if you can share your findings that may be helpful to others seeing this issue.

**Comment by Dweston88** [comment]
@zhenlan I was able to figure it out. Hopefully this helps anyone down the road I spent days upon days trying to figure it out. Listed below is all you have to add when using net.pipe bindings in bold. Everything else in this previous example I posted works.

RUN Import-Module "WebAdministration"; \
	Set-ItemProperty IIS:\Sites\TPS -name EnabledProtocols -Value 'http,net.pipe'; \
	Set-ItemProperty IIS:\Sites\TPS -Name bindings -Value @{protocol='net.pipe'; bindingInformation='localhost/B3484F79-D707-4F0F-AC7C-7EE2F94F29EB/1EE70337-85E3-4D23-AEC8-BBA1769E98D8'} **-Force**

**Comment by zhenlan** [comment]
Thank you for sharing this, @Dweston88.

**Comment by mconnew** [comment]
@Dweston88, where did the guids for your bindingInformation come from?
