### ISSUE TITLE
WCF net.tcp with Transport security mode

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/wcf-docker#28]
_Copied from https://github.com/Microsoft/dotnet-framework-docker/issues/176 by @fedemonte89 _

Hi, I'm trying to use the WcfServiceConsoleApp project in a container turning on the security mode for net.tcp protocol. As a local app it works without any issue, inside the container no.

Do you know any Windows feature to install in order to use the Transport security?

The following is my app.config file:
`<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
  <system.serviceModel>
    <behaviors>
      <serviceBehaviors>
        <behavior name="">
          **<serviceMetadata httpGetEnabled="false" httpsGetEnabled="false" />**
          <serviceDebug includeExceptionDetailInFaults="false" />
        </behavior>
      </serviceBehaviors>
    </behaviors>
    <services>
      <service name="WcfServiceConsoleApp.Service1">
        
        <endpoint binding="netTcpBinding" contract="WcfServiceConsoleApp.IService1" bindingConfiguration="noSecurityBind"/>
        **<endpoint address="mex" binding="mexTcpBinding" contract="IMetadataExchange" />**
        <host>
          <baseAddresses>
            
            <add baseAddress="net.tcp://localhost:808/Service1.svc" />
          </baseAddresses>
        </host>
      </service>
    </services>
    <bindings>
      <netTcpBinding>
        <binding name="noSecurityBind" portSharingEnabled="false">
          **<security mode="Transport" />**
        </binding>
      </netTcpBinding>
    </bindings>
  </system.serviceModel>
</configuration>`

**Comment by Lxiamail** [comment]
@fedemonte89  Transport security default clientcredentialtype is Windows auth. Windows auth uses activedirectory, which is not supported in Windows container. Can you try to use certificate auth?

**Comment by Lxiamail** [comment]
@fedemonte89 WCF net.tcp transport security uses Windows auth by default. Windows auth depends on ActiveDirectory, which is not supported in Windows Container. Can you try to use certificate auth instead?

**Comment by fedemonte89** [comment]
@Lxiamail Thank you for your response. I'm trying to evaluate the effort using Docker and containers for an existing architecture. The transport security is the main feature to get the identity of "caller" and to encrypt the communication.

So I'll try your suggestion. Do you know if it's planned that feature supporting?

**Comment by Lxiamail** [comment]
@fedemonte89 I don't know if Windows container has plan to support ActiveDirectory. As far as I know, it should be replaced by GMSA account. However, due to other priorities, we haven't had a working sample for the scenario. If you like to try out using GMSA account, I would love to hear your experience.
